-- MySQL Script generated by MySQL Workbench
-- Tue 16 Oct 2018 19:33:38 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema boardgamesapp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `boardgamesapp` ;

-- -----------------------------------------------------
-- Schema boardgamesapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `boardgamesapp` ;
USE `boardgamesapp` ;

-- -----------------------------------------------------
-- Table `boardgamesapp`.`profiles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boardgamesapp`.`profiles` ;

CREATE TABLE IF NOT EXISTS `boardgamesapp`.`profiles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(255) NULL,
  `wins` INT NULL,
  `losses` INT NULL,
  `totalGames` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boardgamesapp`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boardgamesapp`.`users` ;

CREATE TABLE IF NOT EXISTS `boardgamesapp`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(255) NULL,
  `lname` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `rememberMeToken` VARCHAR(255) NULL,
  `forgotPasswordToken` VARCHAR(255) NULL,
  `profiles_id` INT NOT NULL,
  PRIMARY KEY (`id`, `profiles_id`),
  INDEX `fk_users_profiles_idx` (`profiles_id` ASC) ,
  CONSTRAINT `fk_users_profiles`
    FOREIGN KEY (`profiles_id`)
    REFERENCES `boardgamesapp`.`profiles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boardgamesapp`.`Games`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boardgamesapp`.`Games` ;

CREATE TABLE IF NOT EXISTS `boardgamesapp`.`Games` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(5024) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boardgamesapp`.`PlayedGames`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boardgamesapp`.`PlayedGames` ;

CREATE TABLE IF NOT EXISTS `boardgamesapp`.`PlayedGames` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Games_id` INT NOT NULL,
  `score` INT NULL,
  PRIMARY KEY (`id`, `Games_id`),
  INDEX `fk_PlayedGames_Games1_idx` (`Games_id` ASC) ,
  CONSTRAINT `fk_PlayedGames_Games1`
    FOREIGN KEY (`Games_id`)
    REFERENCES `boardgamesapp`.`Games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
